#!/bin/sh /etc/rc.common

START=21
STOP=89

USE_PROCD=1

msg() {
	logger -p daemon.info -st "clash[$$]" "$*"
}

start_service() {
	# The ruleset folder is used from tmpfs
	if [ ! -d /tmp/clash/ruleset ]; then
		mkdir -p /tmp/clash/ruleset
		msg "The folder '/tmp/clash/ruleset' was created"
	fi
	if [ ! -L /opt/clash/ruleset ] || [ "$(readlink /opt/clash/ruleset)" != "/tmp/clash/ruleset" ]; then
		rm -rf /opt/clash/ruleset
		ln -s /tmp/clash/ruleset /opt/clash/ruleset
		msg "Created a symlink from '/tmp/clash/ruleset' to '/opt/clash/ruleset'"
	fi

 	/opt/clash/bin/clash -d /opt/clash -t
	if [ $? -ne 0 ]; then
		msg "Clash instance is not started"
		return
	fi

	procd_open_instance
	procd_set_param command /opt/clash/bin/clash -d /opt/clash
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
	msg "Clash instance is started"

}

stop_service() {
	msg "Clash instance has been stopped"

}

reload_service() {
	stop
	start
}

boot() {
	sleep 10
	start
}
